"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['spell_checker_ui.py']
DATA_FILES = []
OPTIONS = {'iconfile':'spellcheck.ico'}

setup(
    name='SpellChecker',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
